### ISSUE TITLE
Hello, I am planning to assemble a CNC machine

### ISSUE THREAD

**Issue by 84864797** [MillenniumMachines/MillenniumOS#71]
Hello, I am planning to assemble a CNC machine, which is a cast iron gantry with a stroke of 300mm * 400mm. Can it be controlled using MillenniumOS?
How CNC Pendant solves the problem？
![QQ截图20240501150954](https://github.com/MillenniumMachines/MillenniumOS/assets/104506675/d64a9a54-756d-4bf5-ac88-13ae19024353)

**Comment by benagricola** [comment]
If the control board you choose can run RepRapFirmware 3.5.0+ with sufficient memory for the global variables that MillenniumOS uses, then yes. Otherwise, no.

A CNC Pendant solves the problem of having to use RRF's inbuilt jog dialogs (which is a big win) but other than that, it doesn't solve much.
